### PR TITLE
fix: unlockConfirm is a number not string

### PR DESCRIPTION
**Pull request by c9s**

### CODE REVIEW

**Comment by adshao** [comment]
Hi @c9s , could you please fix the [Travis CI issue](https://app.travis-ci.com/github/adshao/go-binance/builds/249799032)?

**Comment by c9s** [comment]
done, fixed the formatting issue.

**Comment by gaga5lala** [comment]
@c9s There's also a failed testing about the type
https://app.travis-ci.com/github/adshao/go-binance/builds/250101951
```
...
vet: ./deposit_service_test.go:82:18: cannot convert "12/12" (untyped string constant) to int64
The command "go vet ./..." failed and exited with 2 during .
```

Seems like string is the correct type of deposit API (`GET /sapi/v1/capital/deposit/hisrec (HMAC SHA256)`). Please correct me if I misunderstood.

image

https://binance-docs.github.io/apidocs/spot/cn/#user_data-6

image
https://binance-docs.github.io/apidocs/spot/cn/#user_data

**Comment by c9s** [comment]
Don't have time to fix this, so I am closing this PR

**Pull request closed without merging**
