### PR TITLE
feat(websocket): switch to nhooyr.io/websocket for wasm support

### PR DESCRIPTION
**Pull request by Milerius**
What is achievied:

- Switch from gorilla ws to nhooyr ws
- KeepAlive heartbeat implemented using https://github.com/nhooyr/websocket/issues/265#issuecomment-734499702
- Only spot websocket API switched to nhooyr websocket atm (if you are happy with the result i will also apply the code to future/delivery API)
- Close the websocket using StatusNormalClosure

I do not that have that much experience with golang & websocket, i tested my implementation, it works for me but I don't know if it was the most idiomatic way to do it, feel free to comment and give your opinion so that we can move in the right direction.

It is especially the first time that I have to use a context and I have a little doubt about the lifespan of the context in this specific case, I tried not to break the architecture in place (2 chans quit / done) but suddenly I don't know if on the lifetime side the cancel function of the context will still be available at the time of the websocket closure.

cc @adshao 

Address #284 

Motivation for this pr: I am currently writing a [trading bot](https://github.com/Milerius/mm2-client) that also works in webassembly, having the websocket binance would allow me to have the prices in real time rather than having to do polling in my browser

### CODE REVIEW

**Comment by adshao** [comment]
Hi @Milerius , thanks for this PR. It looks good to me, I will build and test it in my environment to check if everything works.

**Review by adshao — APPROVED** [review]

**Comment by adshao** [comment]
Hi @Milerius , I have tested it, it seems great. Could you please refactor for delivery and futures packages as well?

**Comment by Milerius** [comment]
> Hi @Milerius , I have tested it, it seems great. Could you please refactor for delivery and futures packages as well?

Sure i will do shortly.

**Comment by Milerius** [comment]
> Hi @Milerius , I have tested it, it seems great. Could you please refactor for delivery and futures packages as well?

done @adshao

**Review by adshao — APPROVED** [review]

**Pull request merged**
