### PR TITLE
add websocket support for spot book-ticker

### PR DESCRIPTION
**Pull request by en0ma**
This MR closes https://github.com/adshao/go-binance/issues/155

### CODE REVIEW

**Comment by adshao** [comment]
hi @en0ma , could you please fix these testing issues: https://travis-ci.org/github/adshao/go-binance/builds/756231228 thanks.

**Comment by en0ma** [comment]
> hi @en0ma , could you please fix these testing issues: https://travis-ci.org/github/adshao/go-binance/builds/756231228 thanks.

@adshao I have fixed the failing test

**Comment by cagodoy** [comment]
@adshao Please merge this contribution 👍

**Review by adshao — APPROVED** [review]

**Comment by cagodoy** [comment]
Thanks!

**Pull request merged**
