### PR TITLE
Combined agg trade and book ticker

### PR DESCRIPTION
**Pull request by basnijholt**
Reopening https://github.com/adshao/go-binance/pull/214

### CODE REVIEW

**Comment by adshao** [comment]
hi @basnijholt , could you please fix the vet error: https://app.travis-ci.com/github/adshao/go-binance/builds/253726661

**Comment by basnijholt** [comment]
@adshao, I have to admit I do not understand why this error occurs. Can you give me any suggestions?

**Comment by adshao** [comment]
> @adshao, I have to admit I do not understand why this error occurs. Can you give me any suggestions?

It seems you should delete L419:L443

**Comment by adshao** [comment]
> Can you guys point me to some resource so I can learn how to contribute?
> 
> I don't know how to make a pull request or how things are handled. I only worked alone with git and used github as a central storage for my code.
> 
> I clone it in my in my machine, create a branch, work on it and push to origin?

Please kindly refer to this article to create a pull request from your forked repo: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by basnijholt** [comment]
I have removed the duplicate function now, thanks for the help!

**Comment by vinifrancosilva** [comment]
> > Can you guys point me to some resource so I can learn how to contribute?
> > I don't know how to make a pull request or how things are handled. I only worked alone with git and used github as a central storage for my code.
> > I clone it in my in my machine, create a branch, work on it and push to origin?
> 
> Please kindly refer to this article to create a pull request from your forked repo: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Thank you! Gonna undertand about the fork and if @basnijholt is away from this project, I will make the pull request.

**Comment by basnijholt** [comment]
Should be fixed now! :)

**Comment by adshao** [comment]
> Should be fixed now! :)

thanks so much @basnijholt

**Review by adshao — APPROVED** [review]

**Pull request merged**
