### PR TITLE
changed bool types to string in reduceOnly, closePosition, priceProtect.

### PR DESCRIPTION
**Pull request by size12**
There are should be STRING types in this fields. 
image

BOOL type is still working in single order requests, but not is batch ones.

### CODE REVIEW

**Comment by size12** [comment]
@adshao please check🙂

**Comment by adshao** [comment]
Hi @size12 , could you please add unit tests for this change?

**Comment by maggch97** [comment]
This fix works in my project. Before this fix, I always got error when using BatchOrder [<APIError> code=-1102, msg=Mandatory parameter 'reduceOnly' was not sent, was empty/null, or malformed. <APIError> code=-1102, msg=Mandatory parameter 'reduceOnly' was not sent, was empty/null, or malformed.]}

**Comment by size12** [comment]
@adshao hi, this problem still exists, so please review my PR :)

**Review by adshao — APPROVED** [review]

**Pull request merged**
