### PR TITLE
feat : each api should let users choose it is test net or production.

### PR DESCRIPTION
**Pull request by kunsonx**
Hello there.

I think the client API should let users choose which one is used for testnet or production?

I want to use SDK on my project and some users connect to testnet and other users connect to production env.

If you have more graceful advice please let me know.

Thanks.

### CODE REVIEW

**Comment by adshao** [comment]
This change will break the API compatibility. Could you initialize two API clients, one for mainnet, while the other for testnet, and use the corresponding client for your users.

**Comment by 316181444** [comment]
> This change will break the API compatibility. Could you initialize two API clients, one for mainnet, while the other for testnet, and use the corresponding client for your users.

Good Idea. But WSxxx API doesn't have a client object. so how to do this?

**Comment by 316181444** [comment]
> This change will break the API compatibility. Could you initialize two API clients, one for mainnet, while the other for testnet, and use the corresponding client for your users.

I changed my pull request contents. recover WebSocket APIs changes. I think it may be much better for now.

**Comment by adshao** [comment]
It's not a good idea to set testnet flag in each API function.
For websocket, we have a global var `UseTestnet`.
Furthermore, it's better to create websocket client just like REST API.

**Pull request closed without merging**
