### PR TITLE
fix signature error while the content includes @

### PR DESCRIPTION
**Pull request by xyq-c-cpp**
1. fix #639 , This is the fundamental approach to fix this issue. Fix issue [Signature error when request parameter content includes @]
    1. Currently, only the binance module has been repaired, and other modules have not been involved yet. Do not modify them for now.

### CODE REVIEW

**Comment by adshao** [comment]
Has the bug been confirmed? Is there a better way to fix it without hardcoding the special symbols?

**Comment by adshao** [comment]
https://github.com/adshao/go-binance/pull/639#issuecomment-2519496004

**Comment by xyq-c-cpp** [comment]
> Has the bug been confirmed? Is there a better way to fix it without hardcoding the special symbols?

Yes, I have confirmed that the modified code has been tested in real time environment, for the interface `POST /sapi/v1/sub-account/universalTransfer`.   
Other open-source libraries [binance-futures-connector-python](https://github.com/binance/binance-futures-connector-python) also perform similar processing after URL encoding. At present, this is a perfect approach, it seems. @adshao

**Comment by xyq-c-cpp** [comment]
image

The response appears to be @, which is a secure string and does not require URL encoding. @adshao

**Comment by adshao** [comment]
> > Has the bug been confirmed? Is there a better way to fix it without hardcoding the special symbols?
> 
> Yes, I have confirmed that the modified code has been tested in real time environment, for the interface `POST /sapi/v1/sub-account/universalTransfer`. Other open-source libraries [binance-futures-connector-python](https://github.com/binance/binance-futures-connector-python) also perform similar processing after URL encoding. At present, this is a perfect approach, it seems. @adshao

OK, please add tests for this change and include comments explaining why the ‘@’ symbol must be escaped.

**Comment by xyq-c-cpp** [comment]
In actual testing, when passing in query_string, @ escape or no escape is acceptable. When passing in the body, @ escape is not allowed, @ not escape is allowed. So not escaping is the best solution. @adshao

**Comment by xyq-c-cpp** [comment]
> In actual testing, when passing in query_string, @ escape or no escape is acceptable. When passing in the body, @ escape is not allowed, @ not escape is allowed. So not escaping is the best solution. @adshao

When parameters are passed through request-body, the main issue is that the signature is correct when the @ in the signature content is not escaped; Signature error if escaped. @adshao

**Review by adshao — APPROVED** [review]

**Pull request merged**
