### PR TITLE
The futures module adds the continuous contract Kline rest interface and websocket interface

### PR DESCRIPTION
**Pull request by xyq-c-cpp**
Hello, I used this module and found that the relevant interfaces of the future part of the continuous contract kline were not implemented. So I implemented a copy and hope that the author can incorporate it.

rest api:
image

websocket:
image

### CODE REVIEW

**Comment by adshao** [comment]
chatgpt

**Comment by adshao** [comment]
Code Review: Based on the code alone, it is difficult to determine if the code is "good" or not. However, it appears that the code defines structs and functions for handling continuous kline websocket events, with error handling provided. The code also includes comments explaining the purpose of each struct and function. 

In order to determine if the code is good or not, it would be necessary to examine how it is used within a larger codebase, and whether it effectively accomplishes the desired functionality with good performance and maintainability.

**Comment by xyq-c-cpp** [comment]
@adshao I checked that the naming is not reasonable. I will modify it later. "In order to determine if the code is good or not, it would be necessary to examine how it is used within a larger codebase, and whether it effectively accomplishes the desired functionality with good performance and maintainability." => Do you need some demo examples?

**Comment by adshao** [comment]
> @adshao I checked that the naming is not reasonable. I will modify it later. "In order to determine if the code is good or not, it would be necessary to examine how it is used within a larger codebase, and whether it effectively accomplishes the desired functionality with good performance and maintainability." => Do you need some demo examples?

Sorry, the comment above was created by chatgpt action which is my another project 😄 [chatgpt-code-review-action](https://github.com/adshao/chatgpt-code-review-action) 
I will manually review the code later, thanks.

**Review by adshao — APPROVED** [review]

**Pull request merged**
