### PR TITLE
Fix for Err: <APIError> code=-1021, msg=Timestamp for this request was 1000ms ahead of the server's time.

### PR DESCRIPTION
**Pull request by mariospas**
I used the ubuntu ntp time server to get the timestamp for the secure request. 
With that fix I managed to avoid that error
```
Err: <APIError> code=-1021, msg=Timestamp for this request was 1000ms ahead of the server's time.
```

### CODE REVIEW

**Comment by Krisa** [comment]
Very inefficient to do this at every call 👎 I like the idea, but then we should instead analyze the response and look for the error code `-1021`. And only then, make a one-time call to adjust the server time.

Also I wonder what are these external dependencies in go.mod... I don't think it's needed and Binance provides itself its own server time and it's even already implemented as part of this library https://github.com/adshao/go-binance/blob/735e7f4648600221ddc128083d0a300129991912/server_service.go#L31

**Comment by mariospas** [comment]
You are right that it is inefficient way, but it solves the problem for now. I will try your suggestion.

**Comment by adshao** [comment]
@mariospas Personally I don't think it is the issue of this SDK, you should use `ntpd` or other time synchronization tools to make sure the time of your host running this SDK is synchronized with remote server, for this SDK, we always suppose there is no time issue here.

**Comment by Krisa** [comment]
@adshao - I wouldn't dismiss this idea so quickly. It's sometimes hard (require external sync application), or not possible, and at best requires lots of tooling to be able to change the time machine, especially in cross environment (Windows, Linux, Darwin)... And in case one needs the require permissions to run such tools and do such modifications.

I see for example that the most popular Binance JS library is having such feature https://github.com/jaggedsoft/node-binance-api#troubleshooting. By making a call to that method, it sets an internal flag `timeOffset` https://github.com/jaggedsoft/node-binance-api/blob/d011f5845a91c06a0f4ef32ff08bed31d53cb29e/node-binance-api.js#L1207 used in subsequent signed requests here https://github.com/jaggedsoft/node-binance-api/blob/d011f5845a91c06a0f4ef32ff08bed31d53cb29e/node-binance-api.js#L192

I would have preferred myself `go-binance` to analyse the error code `-1021` somewhere in the central `callAPI` method (https://github.com/adshao/go-binance/blob/master/client.go#L244) and in such case  get the Binance time, set an internal offset and re-do the request. After all this library does not give a way to centralise errors from all different methods and so we don't have a good way to do that as of now. 

Either way, I think that what is done in `node-binance` is at least a very acceptable trade-off which one could use in a hourly or daily cron job to ensure that the time is always quite accurate

**Pull request closed without merging**
