### PR TITLE
Add WsMarkPriceServe: Futures mark price stream

### PR DESCRIPTION
**Pull request by ydm**
https://binance-docs.github.io/apidocs/futures/en/#mark-price-stream

### CODE REVIEW

**Comment by adshao** [comment]
hi @ydm , Could you please run gofmt to format your code? For more information about this error of Travis CI, please refer to https://travis-ci.org/github/adshao/go-binance/builds/734992387

**Comment by ydm** [comment]
> hi @ydm , Could you please run gofmt to format your code? For more information about this error of Travis CI, please refer to https://travis-ci.org/github/adshao/go-binance/builds/734992387

Hey, I'm truly sorry for being so late with the gofmt patch. I saw you merged that into the master. Should I make a new pull request that applies gofmt?

**Comment by adshao** [comment]
> > hi @ydm , Could you please run gofmt to format your code? For more information about this error of Travis CI, please refer to https://travis-ci.org/github/adshao/go-binance/builds/734992387
> 
> Hey, I'm truly sorry for being so late with the gofmt patch. I saw you merged that into the master. Should I make a new pull request that applies gofmt?

Yes, please merge the latest code of master branch and run gofmt, thanks.

**Comment by adshao** [comment]
close this pr since #170 merged

**Pull request closed without merging**
