### PR TITLE
Fix /sapi/v1/sub-account/universalTransfer Signature for this request is not valid.

### PR DESCRIPTION
**Pull request by hlongvu**
A fix for wrong params and formParams set on api /sapi/v1/sub-account/universalTransfer

### CODE REVIEW

**Comment by xyq-c-cpp** [comment]
If `setFormParam ` is not replaced, can the problem be found in `parseRequest ` @hlongvu

**Comment by xyq-c-cpp** [comment]
Have you ever used this interface in real life? I'm testing other similar interfaces with `setFormParam` and see if they work fine @hlongvu

**Comment by hlongvu** [comment]
I am using the fix on my bot and it's working fine.
the original [v2.6.1](https://github.com/adshao/go-binance/releases/tag/v2.6.1) throw the "Signature for this request is not valid" error.
I take a look on the api example here and they put all variable on params https://www.postman.com/api-noob/binance-apis/request/hji0sli/universal-transfer-for-master-account

**Comment by adshao** [comment]
> I am using the fix on my bot and it's working fine. the original [v2.6.1](https://github.com/adshao/go-binance/releases/tag/v2.6.1) throw the "Signature for this request is not valid" error. I take a look on the api example here and they put all variable on params https://www.postman.com/api-noob/binance-apis/request/hji0sli/universal-transfer-for-master-account

Hi @hlongvu , Could you please share the code you used along with the debug log?
In the binance API document, both params in form and query string are accepted: [doc](https://developers.binance.com/docs/sub_account/general-info)

**Comment by hlongvu** [comment]
[debuglog.log](https://github.com/user-attachments/files/18019233/debuglog.log)
@adshao @xyq-c-cpp here is the log for error on my end

Code:

`
masterAccount.Client.NewSubAccountUniversalTransferService().
		FromEmail(masterAccount.AccountEmail).
		ToEmail(subAccountConfig.AccountEmail).
		FromAccountType("SPOT").
		ToAccountType("USDT_FUTURE").
		Asset("USDT").
		Amount(fmt.Sprintf("%.0f", amount)).
		RecvWindow(50000).
		Do(context.Background())
`

**Comment by hlongvu** [comment]
Maybe related https://github.com/ccxt/ccxt/issues/19491

**Comment by adshao** [comment]
> Maybe related [ccxt/ccxt#19491](https://github.com/ccxt/ccxt/issues/19491)

Thank you @hlongvu , I don't think this bug is caused by `setFormParams`, it should be some special symbols in email format which is encoded by URLEncode. @xyq-c-cpp is trying to fix it in #646

**Pull request closed without merging**
